[package]
name = "function_name_generator"
version = "0.1.0"
edition = "2021"



[[bin]]
name = "selector_name"
path = "selector_name.rs"


[dependencies]
hex = "0.4.3"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
itertools = "0.10.1"
rayon = "1.5.1"
